

== MySQL

MySQL intro: https://dev.mysql.com/doc/refman/8.0/en/tutorial.html

=== Creation
``$ mysql -u root -p
``

use your password and adjust it in `application.properties`

`mysql&gt; CREATE DATABASE book_database;`


`mysql&gt; USE book_database;`


`mysql> CREATE TABLE book +
(  +
  id int(11) NOT NULL AUTO_INCREMENT, +
  name varchar(60) NOT NULL, +
  autor varchar(100) NOT NULL, +
  iban int(30) NOT NULL, +
  status int (10) NOT NULL DEFAULT 1, +
  timestamp TIMESTAMP, +
  PRIMARY KEY (id) +
);`

=== Make some data (optional)

`mysql&gt; INSERT INTO BOOK (id,name,autor,iban) VALUES(1,&quot;Grundriss Heidegger&quot;,&quot;Helmuth Vetter&quot;, 9783);`

more data ...

==== Check Table
`mysql> SELECT * FROM book`

you should see something like this:


|===
| bookId | name| autor| iban

|1
|Grundriss Heidegger
|Helmuth Vetter
|9783

|2
|Heidegger
|Oliver Jahraus
|9784

|3
|Heidegger
|Udo Tietz
|9785|
|===

== Quick Start

* `mvn clean install`

* build project

=== Test CRUD operations
Create (GET):
http://localhost:8080/books/add?name=test01&autor=auth01&iban=1234

Create (POST):
`$ curl --data "name=testPost&autor=authPost&iban=1235" http://localhost:8080/books/add`

Get all:
http://localhost:8080/books/all

Get by id:
http://localhost:8080/books/1

Delete by id:
``curl -X DELETE http://localhost:8080/books/delete/1
``